### ISSUE TITLE
First Week Story

### ISSUE THREAD

**Issue by agreenberg18** [cs600f2016/FALL2016#2]
Jane and her friends live in NYC and are bored on a Saturday afternoon.  After seeing a friend post on Instagram an interesting creative piece of art, she realized it was part of an open ended game.  After googling the hashtag she discovers that it was part of an artistic scavenger hunt game. Participants are given a list of materials to collect and are challenged to create an art piece inspired by a given idea within an allotted time frame.  She knew it was something fun that she and her bored friends could do that Saturday.  They managed to find all of the easily accessible materials, along with adding their own flair; and created a homegrown masterpiece.  Later that night the competition ended and they got to see what other teams came up with.  She posted a picture of their masterpiece to Facebook/Instagram and couldn’t wait to see what would be made next week.

**Comment by cicorias** [comment]
This is a "big" story. Sounds like an Epic.  A Story should be "bite size" need of the user - again, no exact science here. But in reality the Development team tries to make User Stories something they can achieve in a single sprint (reality they use 1/2 the time of the sprint as real productivity factors are in the 50 - 60% range; in other words if a developer says I can do that Task in 8 hours - reality is 16 hours - (stories are broken down into tasks) )

## Possible helpers
- https://www.atlassian.com/agile/delivery-vehicles
- https://www.mountaingoatsoftware.com/blog/stories-epics-and-themes
