### ISSUE TITLE
Investigating User Authentication via Firebase

### ISSUE THREAD

**Issue by vjrene** [cs600f2016/FALL2016#3]
Login/Sign Up using Facebook/Google/other Forms
- firebase, facebook API, etc

**Comment by cicorias** [comment]
there are several options. Personally, I'd pick 1 for now and then look at the frameworks to support it.  Facebook has "bits" and Recipes for iOS, Android, Web, etc.  However,  one option is Auth0.com. These guys have made the "configuration" much simpler and provide "bits" that will work with the various platforms.

This is a large "Story" -  I'd break this up into 1 story that just says "login with sample credentials" and we can hard code the Login/Password for now.. Then another story that says " I need to authentication with Facebook so i can ..."

**Comment by noncreativetype** [comment]
9/26 group researched and have a skeleton layout for login page linked to firebase

**Comment by noncreativetype** [comment]
Still need to work on logout function/button hiding and email verification
