### ISSUE TITLE
Investigating Generated code

### ISSUE THREAD

**Issue by vjrene** [cs600f2016/FALL2016#4]
- "Create Team" --> a random token to email/text
- Anyone with that token enters it, is part of the team
- Team as a live list view (firebase)

**Comment by cicorias** [comment]
This happens to be a common "pattern" or Recipe..  

The Planning Poker site does this [Planning Poker.com](https://www.planningpoker.com)

Plus Skype does this now as well.  This is a good low barrier way for people to join a collaboration experience online as they don't have to login, setup identity, etc.
